### ISSUE TITLE
Time format not recognized

### ISSUE THREAD

**Issue by JuliaWiel** [xaviermouy/FishSound_Finder#1]
Hello Xavier,

I try to run your software on my data. Your example works perfectly but when I try with one of my record I have an error. Here the link to download my record https://drive.google.com/file/d/1o-loFw8EwApsE-4Dw0bqfUuXjS7YCuxX/view?usp=sharing. The error seems to come from the time format. I tried to rename my file with the name or yours (67674121.181017060806) but the error remains...
In the deployment file, I modified with my information but it doesn't seem to be link.

**Sound file format**
- Name: SBW1712_20200522_080500
- Type: wave
- Channels: 1
- Sample Rate: 64000 Hz
- Encoding: 24 bit signed
- Length: 5min
- Samples: 19200000

**errors_log**
2021-09-06 10:46:20,709 - ERROR - fishsound_finder.detector - .\data\SBW1712_20200522_080500.wav
2021-09-06 10:46:20,709 - ERROR - fishsound_finder.detector - Exception occurred
Traceback (most recent call last):
  File "c:\users\feltbruker\anaconda3\envs\fishsound_finder\lib\site-packages\fishsound_finder\detector.py", line 386, in main
    raven=raven)
  File "c:\users\feltbruker\anaconda3\envs\fishsound_finder\lib\site-packages\fishsound_finder\detector.py", line 218, in run_detector
    file_timestamp = ecosound.core.tools.filename_to_datetime(infile)[0]
  File "c:\users\feltbruker\anaconda3\envs\fishsound_finder\lib\site-packages\ecosound\core\decorators.py", line 17, in wrapper_listinput
    value = func([*args], **kwargs)
  File "c:\users\feltbruker\anaconda3\envs\fishsound_finder\lib\site-packages\ecosound\core\tools.py", line 49, in filename_to_datetime
    raise ValueError('Time format not recognized:' + file)
ValueError: Time format not recognized:.\data\SBW1712_20200522_080500.wav

**Other question**
With what software could I modify .sav and .yaml?

Thanks for your help!

**Comment by xaviermouy** [comment]
Hi Julia,

I have released version 0.0.4 of FishSound Finder which now accepts the date format of the recordings you are analyzing. You will need to set set a new python environment and do a fresh install of FishSound Finder using "pip install fishsound_finder". I will add an option later on to allow users to use their own date format (I will create a separate issue).  FishSound Finder can be now be used with python versions >= 3.7. Note It will return a warning saying that the RandomForest model was created by a previous version of scikits-learn. You can ignore it for now.

Regarding your other questions:
- .sav files can be loaded in python using scikits-learn or pickle. You typically don't want to modify this file manually.
- .yml files can be opened with any text editor (e.g. NotePad++). You will need to edit this file manually to modify spectrogram settings, frequency bands, etc
